btsync:
  image: kartoza/btsync
  hostname: btsync.data.inasafe.org
  volumes:
    - ./data:/web
  environment:
    # This should be the read only key
    - SECRET=BSU2UCAVRV7P4CHRYOZGIRQ2VN6CH4JP3
    - DEVICE=readonly-master.data.inasafe.org
  links:
    - sftpbackup:sftpbackup
  restart: on-failure:5

sftpbackup: &sftpbackup
  image: kartoza/sftp-backup:1.0
  hostname: sftpbackup
  volumes:
    # this folder is used to store local backups from pg dbbackup
    - ./sftp_backup:/backups
    # this folder is used as target folder/source where the backup comes from
    # this backup comes from dbbackup
    - ./data:/data_backup
  environment:
    - DUMPPREFIX=data.inasafe.org
    - DAILY=4
    - MONTHLY=12
    - YEARLY=3
    # set this to the target/source folder where the backup comes from
    - TARGET_FOLDER=/data_backup
    # You can override this in sftp_credential.env
    - SFTP_DIR=/inasafe/data.inasafe.org/
  env_file:
    - sftp_credential.env
  restart: on-failure:5

apache:
  build: docker
  hostname: apache.data.inasafe.org
  volumes:
    - ./data:/var/www/html:ro
    - ./resources:/var/www/resources:ro
  ports:
    - "8190:80"
  restart: on-failure:5

